### PR TITLE
Support for helm chart galaxy-stable

### PR DESCRIPTION
**Pull request by pcm32**
This is the equivalent PR to the one done on cloud-deploy-kubenow https://github.com/phnmnl/cloud-deploy-kubenow/pull/77 to use the newer Helm chart galaxy-stable.

### CODE REVIEW

**Comment by andersla** [comment]
Thanks @pcm32 ! The helm-values file is just renamed (and I had forgotten to add it after rename).

**Comment by pcm32** [comment]
Yes, but what I meant was that it shouldn't be renamed to a generic name, but rather keep its release identity.

**Comment by andersla** [comment]
OK, but to me the helm-values-file look generic to a 1.5.5 galaxy chart version.
All variables are in the default/main.yml
I could rename to galaxy-helm-vals-v1.5.5.yml ?
Or let's just deal with it when there is a new galaxy 18 version? :-)

**Comment by andersla** [comment]
We can continue refactoring when the code is in place

**Comment by pcm32** [comment]
Yes, probably only few variables should be set on the defaults and most of them on helm config file for each release.

Considering that we need to keep in the meantime phnmnl/cloud-deploy-kubenow and phnmnl/cloud-deploy-kubenow-cerebellin, I would suggest avoiding successive refactoring unless really needed, as you will need to re-apply it all on the other repos.

**Pull request merged**
